version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew clean build -x test
  post_build:
    commands:
      - mv build/libs/app.jar .

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'

artifacts:
  files:
    - app.jar
    - appspec.yml
    - scripts/**
    - writerswalk.service