version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Gradle 빌드 시작..."
      - chmod +x gradlew
      - ./gradlew clean build -x test
  post_build:
    commands:
      - echo "JAR 파일을 밖으로 꺼냅니다..."
      - rm -f build/libs/*-plain.jar
      - mv build/libs/*.jar .
artifacts:
  files:
    - "*.jar"
    - appspec.yml
    - scripts/**