spring:
  application:
    name: writers-walk-backend
  profiles:
    active: dev

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true